function [mapcomPrim1,mapcomDual1] = MapcomD(modl1,mail1,intg1, ...
                                             numerptgd,listComDual1, ...
                                             numerptgp,listComPrim1)
% DUREISSEIX David  L.M.G.C. SYSTEMES MULTICONTACTS  le 25 / 08 / 2003


[mapcomDual1,junk] = MapcomB2(modl1,mail1,intg1, ...
                              numerptgd,listComDual1, ...
                              [],[], ...
                              'DUAL');
[mapcomPrim1,junk] = MapcomB2(modl1,mail1,intg1, ...
                              numerptgp,listComPrim1, ...
                              [],[], ...
                              'PRIMAL');
